tags:
  - Tasks
summary: Delete task
operationId: deleteTask
description: 'Delete a task with payload'
security:
  - bearerAuth: []
parameters:
  - in: path
    name: id
    required: true
    schema:
      type: string
      example: '65ca67e7ae7f10c88b598384'
responses:
  '204':
    description: The task was deleted successfully.
  '401':
    $ref: '../../../components/responses/401.yaml'
  '404':
    $ref: '../../../components/responses/404.yaml'
