openapi: 3.1.0
info:
  version: 1.0.0
  title: ContactsApp
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: ContactsApp for saved or changed, contacts. We have auth, and we found only contacts, which you created. Please use this App!
servers:
  - url: http://localhost:3000
paths:
  /boars:
    get:
      $ref: ../swagger/paths/boars/get.yaml
    post:
      $ref: ../swagger/paths/boars/post.yaml
  /boars/{id}:
    get:
      $ref: ../swagger/paths/boars/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/boars/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/boars/{id}/delete.yaml
  /columns:
    post:
      $ref: ../swagger/paths/columns/post.yaml
  /columns/{id}:
    patch:
      $ref: ../swagger/paths/columns/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/columns/{id}/delete.yaml
  /tasks:
    post:
      $ref: ../swagger/paths/tasks/post.yaml
  /tasks/{id}:
    patch:
      $ref: ../swagger/paths/tasks/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/tasks/{id}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      security:
        - bearerAuth: []
      $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email/post.yaml
  /auth/reset-password:
    post:
      $ref: ../swagger/paths/auth/reset-password/post.yaml
  /auth/get-oauth-url:
    get:
      $ref: ../swagger/paths/auth/Google-Auth/get.yaml
  /auth/confirm-google-auth:
    post:
      $ref: ../swagger/paths/auth/Google-Login/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
